### ISSUE TITLE
Publish react app

### ISSUE THREAD

**Issue by dvovk** [erigontech/erigonwatch#1]
I need to have ability to publish react application without bothering DevOPS team.

**Comment by michelemodolo** [comment]
By doing the following steps you will be autonomous in publishing your app every time you need to publish a new version of it:

1) `ssh -i <your private key> app@app-bm-diagnostics-n1-test.erigon.io`
2) `cd  /app/erigonwatch`
3) `git pull`

Then your updated app is served at `testdiag.erigon.io` 

Of course _if you will `git checkout`  any specific branch (or tag) and `git pull`  then your app is visualised according to that branch (or tag) code._
So you are now independent and also have a lot of flexibility for your experiments/development.

In the future we may want to create a pipeline for you (when we'll have time).

**Comment by michelemodolo** [comment]
@dvovk I now put this issue "in review" and you are the reviewer: if you are satisfied please change the status of this issue from "in review" to "done"
